version: "3"
services:
  clin-fhir-server:
    image: chusj/clin-fhir-server:a0b3f5c
    deploy:
      placement:
        constraints:
          - node.labels.app_role == generic
      resources:
        limits:
          cpus: '2.00'
          memory: 2048M
        reservations:
          cpus: '1.00'
          memory: 1024M
    environment:
      HAPI_DATASOURCE_DRIVER: "org.postgresql.Driver"
      HAPI_DATASOURCE_URL: "jdbc:postgresql://clin-fhir-server-postgres:5432/hapi"
      HAPI_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQL95Dialect"
      HAPI_DATASOURCE_USERNAME: "admin"
      HAPI_DATASOURCE_PASSWORD: "admin"
      HAPI_AUTH_SERVER_URL: "https://clin.ferlab.bio:8543"
      HAPI_AUTH_REALM: "clin"
      HAPI_DISABLE_SSL_VALIDATION: "false"
      HAPI_SERVER_ADDRESS: "https://clin.ferlab.bio/fhir/"
      JAVA_OPTS: "-server -Xmx1024m -Djava.net.preferIPv4Stack=true -Djava.awt.headless=true -XX:+UseContainerSupport"
    ports:
      - "8080:8080"
    networks:
      - proxy
      - clin-fhir-internal
  clin-fhir-server-postgres:
    image: postgres
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.labels.app_role == generic
          - node.labels.state_anchor == true
      resources:
        limits:
          cpus: '2.00'
          memory: 2048M
        reservations:
          cpus: '1.00'
          memory: 1024M
    environment:
      POSTGRES_DB: 'hapi'
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'admin'
    command: -c 'shared_buffers=256MB' -c 'work_mem=4MB' -c 'maintenance_work_mem=64MB' -c 'max_worker_processes=8'
    volumes:
      - clin-fhir-postgres:/var/lib/postgresql/data
    networks:
      - clin-fhir-internal
volumes:
  clin-fhir-postgres:
networks:
  clin-fhir-internal:
    external: true
  proxy:
    external: true
