version: '3.5'

services:
  patient:
    image: chusj/clin-proxy-api-patient-service:$DEFAULT_PROD_VERSION
    ports:
      - "4000:4000"
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.labels.app_role == generic
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - patient.env
    secrets:
      - source: certificate_v2_certificate
        target: certificate_certificate
      - source: certificate_v2_key
        target: certificate_key
  variant:
    image: chusj/clin-proxy-api-variant-service:$DEFAULT_PROD_VERSION
    ports:
      - "5001:5001"
    deploy:
      replicas: 3
      placement:
        constraints:
        - node.labels.app_role == generic
      resources:
        limits:
          cpus: '1.00'
          memory: 512M
        reservations:
          cpus: '0.50'
          memory: 256M
    networks:
      - clinnet
      - proxy
    env_file:
      - variant.env
    secrets:
      - source: certificate_v2_certificate
        target: certificate_certificate
      - source: certificate_v2_key
        target: certificate_key
  meta:
    image: chusj/clin-proxy-api-meta-service:$DEFAULT_PROD_VERSION
    ports:
      - "7000:7000"
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.labels.app_role == generic
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - meta.env
    secrets:
      - source: certificate_v2_certificate
        target: certificate_certificate
      - source: certificate_v2_key
        target: certificate_key
  gene:
    image: chusj/clin-proxy-api-gene-service:$DEFAULT_PROD_VERSION
    ports:
      - "5002:5002"
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.labels.app_role == generic
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - gene.env
    secrets:
      - source: certificate_v2_certificate
        target: certificate_certificate
      - source: certificate_v2_key
        target: certificate_key
  hpo:
    image: chusj/clin-proxy-api-hpo-service:$DEFAULT_PROD_VERSION
    ports:
      - "8400:8400"
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.labels.app_role == generic
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    networks:
      - clinnet
      - proxy
    env_file:
      - hpo.env
    secrets:
      - source: certificate_v2_certificate
        target: certificate_certificate
      - source: certificate_v2_key
        target: certificate_key

secrets:
  certificate_v2_certificate:
    external: true
  certificate_v2_key:
    external: true

networks:
  clinnet:
    external: true
  proxy:
    external: true
